edit collaborations page
NCAR/geocat-hugo pull request #6
Opened 2024-11-06 16:42 UTC by jukent

Adds mini gallery of Cookbooks and larger sections for each collaboration. Text needs to be fleshed out and possibly some more visually appealing elements.

2024-11-06 20:39 UTC, philipc2 commented
Should we consider including UXarray's collaboration with the DOE SEATS Project and other efforts? Any thoughts @erogluorhan ?

2024-11-06 21:43 UTC, jukent commented
@philipc2 it's set up so that editing `data/collaborations.yml` can add any number of sections.

2024-11-06 22:09 UTC, erogluorhan commented
> Should we consider including UXarray's collaboration with the DOE SEATS Project and other efforts? Any thoughts @erogluorhan ?

Yes, definitely!

2024-11-07 18:59 UTC, philipc2 requested changes
Nice work! A few small suggestions.

2024-11-07 18:59 UTC, philipc2 commented on data/collaborations.yml
> +    description: "CUPiD stands for the CESM Unified Postprocessing and Diagnostics. This project handles a lot of data standartdization and computation for CESM."
```suggestion
    description: "CESM Unified Postprocessing and Diagnostics (CUPiD) is a Python framework for generating diagnostics from CESM that enables and integrates timeseries file generation, data standardization, diagnostics, and metrics from all CESM components."
```

For consistency with the blurb above on ESDS

> "Earth System Data Science (ESDS) is a community building effort at..."

Also modified the description slightly to align with the description online

2024-11-07 18:59 UTC, philipc2 commented on data/collaborations.yml
> +    description: "Earth System Data Science (ESDS) is a community building effort at NSF NCAR / UCAR to bring geoscientists and geoscientific software engineers together to share new tools, ideas, an
```suggestion
    description: "Earth System Data Science (ESDS) is a community building effort at NSF NCAR / UCAR that brings geoscientists and geoscientific software engineers together to share new tools, ideas, and techniques for the evolving best practices with big data Python."
```

2024-11-07 18:59 UTC, philipc2 commented on content/collaborations/_index.md
> +description: "GeoCAT team members are involved in many other community software engineering efforts. Here are our most frequent collaborations:"
```suggestion
description: "The GeoCAT team is involved in many community software engineering efforts. Here are our most frequent collaborations:"
```

2024-11-07 18:59 UTC, philipc2 commented on content/news/ams2025.md
> +title: "Register for GeoCAT’s short course at AMS 2025!"
_**r/unexpectedfactorial**_

This is a very slight nit-pick, but consider dropping the exclamation point from the year?

2024-11-07 19:02 UTC, philipc2 commented
> @philipc2 it's set up so that editing `data/collaborations.yml` can add any number of sections.

Sounds good! I'll open up a PR with UXarray collaborations once this one is merged.

2024-11-07 20:18 UTC, jukent commented on content/news/ams2025.md
> +title: "Register for GeoCAT’s short course at AMS 2025!"
Don't want it to look like a factorial

2024-11-07 20:41 UTC, jukent commented
Thanks for the edits @philipc2 I'm going to merge this now so that you can work on the UXarray addition.

2024-11-07 20:41 UTC, merged